export enum Specialization {
    SMARTPHONE_REPAIR = 'SMARTPHONE_REPAIR',
    TABLET_REPAIR = 'TABLET_REPAIR',
    LAPTOP_REPAIR = 'LAPTOP_REPAIR',
    DESKTOP_REPAIR = 'DESKTOP_REPAIR',
    MAC_SPECIALIST = 'MAC_SPECIALIST',
    DATA_RECOVERY = 'DATA_RECOVERY',
    GAMING_CONSOLE = 'GAMING_CONSOLE',
    SOFTWARE_REPAIR = 'SOFTWARE_REPAIR',
    GENERAL_ELECTRONICS = 'GENERAL_ELECTRONICS'
}