apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: <base64-encoded-mongo-username>
  MONGO_INITDB_ROOT_PASSWORD: <base64-encoded-mongo-password>
