apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: your-customer-image:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: MONGO_URI
            - name: NATS_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: NATS_SERVER_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: JWT_SECRET
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
