# Global configurations
global:
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP

# MongoDB configurations
mongodb:
  image: mongo:7.0-jammy
  port: 27017
  rootUsername: alaa
  rootPassword: polytec
  dataVolumeName: mongo-data

# NATS configurations
nats:
  image: nats:2.9-alpine
  clientPort: 4222
  monitoringPort: 8222

# JWT Secret
jwtSecret: "123456789@Devopsproj"

# Services configurations
services:
  client:
    port: 3000
  apiGateway:
    port: 3030

# Resource limits
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Prometheus
prometheus:
  scrapeInterval: 15s
  evaluationInterval: 15s

# Grafana
grafana:
  adminUser: admin
  adminPassword: "secureP@ssw0rd123!"
  dashboards:
    default:
      kubernetes-pods:
        json: |
          {
            "annotations": {
              "list": []
            },
            "editable": true,
            "panels": [
              {
                "title": "Pod Status",
                "type": "gauge",
                "datasource": "Prometheus",
                "targets": [
                  {
                    "expr": "sum(kube_pod_status_phase{phase=\"Running\"}) / sum(kube_pod_status_phase) * 100",
                    "legendFormat": "Running Pods %"
                  }
                ]
              },
              {
                "title": "Pod CPU Usage",
                "type": "graph",
                "datasource": "Prometheus",
                "targets": [
                  {
                    "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod)",
                    "legendFormat": "{{pod}}"
                  }
                ]
              },
              {
                "title": "Pod Memory Usage",
                "type": "graph",
                "datasource": "Prometheus",
                "targets": [
                  {
                    "expr": "sum(container_memory_usage_bytes{container!=\"\"}) by (pod)",
                    "legendFormat": "{{pod}}"
                  }
                ]
              }
            ],
            "refresh": "10s",
            "schemaVersion": 33,
            "title": "Kubernetes Pods Overview",
            "version": 1
          }
  datasources:
    datasources.yaml:ml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true

persistence:
  enabled: true
  size: 10Gi

service:
  type: LoadBalancer
